### ISSUE TITLE
Resolve generated breaks, this may be caused by held packages

### ISSUE THREAD

**Issue by desynk** [s-h-3-l-l/katoolin3#14]
Hello! when attempting to install many tools using katoolin3 I get the following error: 

```
Reading package lists...
Error with package armitage: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Trying to ignore this...
Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 717, in install
    self._cache[pkg].mark_install()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1483, in mark_install
    fixer.resolve(True)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/katoolin3", line 1169, in <module>
    main()
  File "/usr/local/bin/katoolin3", line 1102, in main
    choice()
  File "/usr/local/bin/katoolin3", line 929, in install_all_packages
    APT.install(all_packages())
  File "/usr/local/bin/katoolin3", line 726, in install
    self._cache[pkg].mark_delete()
  File "/usr/lib/python3/dist-packages/apt/package.py", line 1458, in mark_delete
    fix.resolve()
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
The strange thing is that some tools install successfully, while most of them do not. For instance, the tool "bulk extractor" installed perfectly, while armitage did not. I have verified that I have all of the dependencies installed, and that I am not holding broken packages. Any pointers?

**Comment by s-h-3-l-l** [comment]
> I have verified that I have all of the dependencies installed, and that I am not holding broken packages.

The only remaining explanation I know would be that ```armitage``` requires other versions of the dependencies you have installed.
Unfortunately I can't fix these issues with katoolin3, you have to look into it manually and identify
the versions needed.

You could try starting katoolin3 in one terminal window and in another you could run
```
sudo aptitude install armitage;
```
since aptitude has better dependency management. This should also show you more specific error messages than the exception above.

As a last resort you always can do
```
sudo apt-get clean;
sudo dpkg --configure -a;
sudo apt-get install -f;
```
or download the erroneous packages manually from [tools.kali.org](https://tools.kali.org/tools-listing) .

**Comment by s-h-3-l-l** [comment]
Note: Since this is a highly specific error that cannot be programmatically fixed by katoolin3 I will mark this issue as __question__ and not __bug__ and will point everyone to this issue who encounters the same error.

**Comment by s-h-3-l-l** [comment]
I pinned this issue.
Since there currently is no conversation in here I will close this issue.
